app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api import views


app_name = "api"


router = DefaultRouter()
router.register("postcodes", views.PostcodeModelViewSet, basename="postcodes")

urlpatterns = [
    path("", include(router.urls)),
    path("standard-validation/", views.StandardValidationView.as_view(), name="standard-validation"),
    path("advanced-validation/", views.AdvancedValidationView.as_view(), name="advanced-validation"),
    path("threefiver/", views.ThreeFiverView.as_view(), name="threefiver"),
]

app/db_manager/urls.py
from django.urls import path, include
from db_manager.views import db_manager, postcode_upload

app_name = "db_manager"

urlpatterns = [
    path("", db_manager, name="db-manager"),
    path("postcode-upload", postcode_upload, name="postcode-upload"),
]

app/postcodes/urls.py
from core.views import IndexTemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/', include('user.urls')),
    path("db/", include("db_manager.urls")),
    path('api/', include('api.urls')),
    re_path(r"^.*$", IndexTemplateView.as_view(), name="entry-point"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path("current-user/", views.CurrentUserView.as_view(), name="current-user"),

]

app/core/models.py
from django.db import models


class PostcodeModel(models.Model):
    """Model for uk postcode"""
    postcode = models.CharField(max_length=254, unique=True)
    lat = models.CharField(max_length=254, blank=True)
    long = models.CharField(max_length=254, blank=True)
    county = models.CharField(max_length=254, blank=True)
    district = models.CharField(max_length=254, blank=True)
    ward = models.CharField(max_length=254, blank=True)
    constituency = models.CharField(max_length=254, blank=True)

    def __str__(self):
        return f"{self.postcode}"

app/api/views.py
from core.permissions import IsAdminOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import status, views, filters
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from ukpostcodeutils import validation
from core.models import PostcodeModel
from api.serializers import PostcodeModelSerializer
from django.shortcuts import get_object_or_404
from django.forms.models import model_to_dict


class StandardValidationView(views.APIView):
    """View for the standard validation"""
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        return Response({"message": "Validate UK Postcode"}, status=status.HTTP_200_OK)


    def post(self, request):

        postcode = request.data["postcode"]
        postcode = postcode.replace(" ", "")
        response = validation.is_valid_postcode(postcode)
        if response:
            result = "Valid"
        else:
            result = "Invalid"

        return Response({"result": result}, status=status.HTTP_200_OK)

class AdvancedValidationView(views.APIView):
    """View for the advanced validation"""
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        return Response({"message": "Validate UK Postcode"}, status=status.HTTP_200_OK)


    def post(self, request):

        postcode = request.data["postcode"]
        postcode = postcode.replace(" ", "")

        uk_postcode = PostcodeModel.objects.filter(postcode=postcode).first()

        if uk_postcode:
            uk_postcode = model_to_dict(uk_postcode)
            return Response({"result": uk_postcode}, status=status.HTTP_200_OK)
        else:
            return Response({"result": "Invalid"}, status=status.HTTP_200_OK)


class ThreeFiverView(views.APIView):
    """View for ThreeFiver"""

    permission_classes = (IsAuthenticated,)

    def get(self, request):

        numbers = ["Three"*(i%3==0) + "Five"*(i%5==0) or i for i in range(1, 101)]


        return Response({"numbers": numbers}, status=status.HTTP_200_OK)



class PostcodeModelViewSet(viewsets.ModelViewSet):
    """Viewset for Postcode Model"""
    permission_classes = (IsAuthenticated,)
    serializer_class = PostcodeModelSerializer
    filter_backends = (filters.SearchFilter, filters.OrderingFilter, DjangoFilterBackend)
    filterset_fields = ["postcode",]
    search_fields = ("postcode",)
    ordering_fields = "__all__"
    queryset = PostcodeModel.objects.all().order_by("postcode")

    def get_queryset(self):
        queryset = self.queryset
        return queryset






# {
# "postcode" : "BD177JW"
# }
#
# {
# "postcode" : "G120YN"
# }
#

app/core/views.py
from django.views.generic.base import TemplateView
from django.conf import settings



class IndexTemplateView(TemplateView):
    """For serving Vue.js frontend"""
    def get_template_names(self):
        if settings.DEBUG:
            template_name = "index-dev.html"
        else:
            template_name = "index.html"
        return template_name

app/db_manager/views.py
import pandas as pd
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect
from django.shortcuts import render

from core.models import PostcodeModel


@user_passes_test(lambda u: u.is_superuser)
def db_manager(request):
    return render(request, "db-manager.html", )


@user_passes_test(lambda u: u.is_superuser)
def postcode_upload(request):
    """View for uploading data to database """
    if request.method == "POST":
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            critical_error = "Incorrect file format. Please upload CSV file"
            return render(request, "postcode-upload.html",
                {"critical_error": critical_error, })
        dataset = pd.read_csv(csv_file, encoding="utf-8-sig")

        for code in dataset.itertuples():
            PostcodeModel.objects.create(
                postcode=code.postcode,
                lat=code.lat,
                long =code.long,
                county=code.county,
                district=code.district,
                ward=code.ward,
                constituency=code.constituency,
            )

        return redirect("/")

    return render(request, "postcode-upload.html", )

app/user/views.py
from rest_framework.views import APIView
from rest_framework.response import Response


class CurrentUserView(APIView):
    """Checking for logged-in user"""

    def get(self, request, *args, **kwargs):
        if str(request.user) != "AnonymousUser":
            return Response({"email": request.user.email, "admin": request.user.is_superuser, "username": str(request.user)})
        else:
            return Response({"error": "Anonymous"})

app/db_manager/templates/db-manager.html
{% extends "base.html" %} {% load staticfiles %}


{% block content %}

<div id="page-index">
  <div class="dashboard-cards">
    <div class="row plain-element">
      <div class="col s12 m12 l12  plain-element">
        <div class="row row-title plain-element">

          <br><br><br>


        </div>
      </div>
      <div class="row plain-element">

        <div class="col s12 m12 l2 plain-element" id="activeTrendsColumn">
          <div class="row plain-element">
            <div class="card card-side card-side-left">
              <div class="section-link">

                <a href="{% url 'db_manager:postcode-upload' %}"><i class="fas fa-envelope"></i> &nbsp; Postcode Upload
                </a>

              </div>

            </div>
          </div>

        </div>


      </div>

    </div>
  </div>

  {% endblock %}

app/db_manager/templates/postcode-upload.html
{% extends "base.html" %} {% load staticfiles %}


{% block content %}

<div id="page-index">
  <div class="dashboard-cards">
    <div class="row plain-element">
      <div class="col s12 m12 l12  plain-element">
        <div class="row row-title plain-element">

          <br><br><br>


        </div>
      </div>
      <div class="row plain-element">


        <div class="col s12 m12 l3 plain-element" id="activeTrendsColumn">
          <div class="row bordered">
            <div class="card card-side">
              <div class="section-heading">
                Upload <b> File </b>
              </div>
              <form action="{% url 'db_manager:postcode-upload' %}" class="col s12 plain-element add-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                 <div class="row plain-element left-align">
                  <div class="file-field input-field csv-field">
                    <div class="btn btn-file">
                      <span>File:</span>
                      <input type="file" name="csv_file" id="csv_file" accept=".csv" required="True"
                             class="form-control">
                    </div>
                    <div class="file-path-wrapper">
                      <input class="file-path validate csv-input" type="text">
                    </div>
                  </div>
                </div>

                <br>
                <div class="row plain-element">
                  <button class="btn btn-submit waves-effect waves-light" type="submit" name="action">Submit

                  </button>


                </div>

              </form>


            </div>


          </div>
        </div>

      </div>


    </div>

  </div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>UK Postcodes </title>
  <meta name="Description"  content="UK Postcodes">

  <!-- Materialize-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- FontAwesome Styles-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
        integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
  <!-- Fonts-->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600&display=swap" rel="stylesheet">

  <!-- Material Icons-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Custom Styles-->
  <link href="{% static 'css/custom-styles.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/data.css' %}" rel="stylesheet"/>


  {% block extrahead %}

  {% endblock %}
</head>

<body>
<div id="wrapper">
  <!-- TOP NAVBAR -->
  {% block navbar %}
  <nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="https://www.scurri.com/wp-content/uploads/2021/01/Group-3.svg" alt="Scurri" class="img-logo">

      </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
       {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <li><span><a class="nav-link" href="/admin/">Admin </a></span>
          </li>
           <li><span><a class="nav-link" href="{% url 'db_manager:db-manager' %}">DB Manager</a></span>
          </li>
        {% endif %}
      <li>
          <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            <span><button class="nav-button">Logout</button></span>
          </form>
        </li>

      {% else %}
         <li><span><a class="nav-link" href="{% url 'account_login' %}">Login</a></span>
        </li>
        {% endif %}
    </ul>
  </nav>

  {% endblock %}

  {% block content %}

  {% endblock %}

  <!-- /. WRAPPER  -->
  <div class="footer">
    <p><a target="_blank" href="https://www.lukaszmalucha.com/">Privacy Policy</a> • © 2021 - All Rights Reserved • Powered by Lukasz Malucha&trade;</p>
  </div>
</div>
<!-- Materialize Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

{% block js %}
{% endblock %}

</body>

</html>

app/templates/index-dev.html
<!DOCTYPE html>
{% extends "base.html" %} {% load staticfiles %}
{% load render_bundle from webpack_loader %}
{% block extrahead %}
<link href="{% static 'css/data.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}


<noscript>
    <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to
        continue.</strong>
</noscript>
<div id="app">

    {% render_bundle 'app' %}

</div>




{% endblock %}

app/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %} {% load staticfiles %}
{% block content %}


<noscript>
  <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to
    continue.</strong>
</noscript>
<div id="app">
</div>


{% endblock %}

{% block js %}
<script src="https://assignmentlukasz.s3-eu-west-1.amazonaws.com/static/dist/bundle.js"></script>
{% endblock %}